use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};

use crate::core::settings::read_settings;

/// One sub project attached to a config queue. Queues persist as a JSON
/// list in `<workspace>/config/queues.json` (the config page's workspace
/// folder); the sub projects are embedded in their owning queue.
#[derive(Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ConfigProject {
    pub uuid: String,
    pub name: String,
    /// `imported` (picked from the import area) or `disk` (directory
    /// picked from the file manager).
    pub source: String,
    /// Package name when the project comes from the import area.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub package_name: Option<String>,
    /// Project directory: the imported package folder or the path picked
    /// from disk.
    pub root_path: String,
    /// Original content location: the import area's package folder or the
    /// directory picked from disk; used by the record commands.
    #[serde(default)]
    pub source_path: String,
    pub created_at: String,
    /// Selected template name (from the templates page); absent until one
    /// is saved through `save_config_template`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub template_name: Option<String>,
    /// Modify-config time recorded when the template is saved.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config_time: Option<String>,
    /// Config start time; present once the configuration was started.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
    /// Whether the configuration was started; started projects show in
    /// the project directory.
    #[serde(default)]
    pub started: bool,
    /// Whether the contents were copied into the config area (recorded).
    #[serde(default)]
    pub recorded: bool,
}

#[derive(Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ConfigQueue {
    pub name: String,
    pub uuid: String,
    pub queue_type: String,
    pub created_at: String,
    #[serde(default)]
    pub projects: Vec<ConfigProject>,
}

fn workspace_dir(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    let settings = read_settings(app);
    let trimmed = settings.workspace_path.trim().to_string();
    if trimmed.is_empty() {
        return Err("请先在「设置 → 存储」中选择工作空间路径".to_string());
    }
    let dir = PathBuf::from(trimmed);
    if !dir.is_dir() {
        return Err("工作空间路径不存在，请重新选择".to_string());
    }
    Ok(dir)
}

fn config_dir(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    Ok(workspace_dir(app)?.join("config"))
}

fn queues_path(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    Ok(config_dir(app)?.join("queues.json"))
}

pub fn load_queues(app: &tauri::AppHandle) -> Result<Vec<ConfigQueue>, String> {
    let path = queues_path(app)?;
    match fs::read_to_string(&path) {
        Ok(content) => Ok(serde_json::from_str(&content).unwrap_or_default()),
        Err(_) => Ok(Vec::new()),
    }
}

pub fn save_queues(app: &tauri::AppHandle, list: &[ConfigQueue]) -> Result<(), String> {
    let dir = config_dir(app)?;
    fs::create_dir_all(&dir).map_err(|e| format!("无法创建配置区目录：{e}"))?;
    let content = serde_json::to_string_pretty(list).map_err(|e| e.to_string())?;
    fs::write(queues_path(app)?, content).map_err(|e| e.to_string())
}

#[tauri::command]
pub fn list_config_queues(app: tauri::AppHandle) -> Result<Vec<ConfigQueue>, String> {
    load_queues(&app)
}

/// Creates a new config queue. The uuid is generated by the frontend and
/// must be unique across all queues; the timestamp comes from the
/// frontend in local time (`YYYY-MM-DD HH:mm:ss`) and is stored as-is.
#[tauri::command]
pub fn create_config_queue(
    app: tauri::AppHandle,
    name: String,
    uuid: String,
    queue_type: String,
    created_at: String,
) -> Result<ConfigQueue, String> {
    let name = name.trim().to_string();
    if name.is_empty() {
        return Err("队列名称不能为空".to_string());
    }
    let uuid = uuid.trim().to_string();
    if uuid.is_empty() {
        return Err("队列编号不能为空".to_string());
    }
    let mut list = load_queues(&app)?;
    if list.iter().any(|q| q.uuid == uuid) {
        return Err("队列编号已存在，请重新生成".to_string());
    }

    let queue = ConfigQueue {
        name,
        uuid,
        queue_type: queue_type.trim().to_string(),
        created_at,
        projects: Vec::new(),
    };
    list.push(queue.clone());
    save_queues(&app, &list)?;
    Ok(queue)
}

/// True when the queue already holds an equivalent project: imported
/// projects compare by package name, disk projects by their package name
/// (card name when no package name is set).
fn is_duplicate(queue: &ConfigQueue, project: &ConfigProject) -> bool {
    queue.projects.iter().any(|existing| match project.source.as_str() {
        "imported" => match (&existing.package_name, &project.package_name) {
            (Some(a), Some(b)) => !a.is_empty() && a == b,
            _ => false,
        },
        _ => match (&existing.package_name, &project.package_name) {
            (Some(a), Some(b)) => !a.is_empty() && a == b,
            _ => existing.name == project.name,
        },
    })
}

/// Recursively copies the contents of `src` into `dst`.
fn copy_dir_all(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let dest = dst.join(entry.file_name());
        if entry.file_type()?.is_dir() {
            copy_dir_all(&entry.path(), &dest)?;
        } else {
            fs::copy(entry.path(), &dest)?;
        }
    }
    Ok(())
}

/// Imported projects: record-only at attach time; the content copy into
/// `<workspace>/config/package/<package name>/` happens on the explicit
/// record action (记录项目 / 记录全部项目).
fn prepare_imported_project(
    app: &tauri::AppHandle,
    project: &mut ConfigProject,
) -> Result<(), String> {
    let package_name = project
        .package_name
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .ok_or_else(|| "导入项目缺少包名信息".to_string())?
        .to_string();
    let source = workspace_dir(app)?
        .join("import")
        .join("package")
        .join(&package_name);
    if !source.is_dir() {
        return Err(format!(
            "导入区未找到包名「{package_name}」的内容，请先在导入区完成导入"
        ));
    }
    let source_str = source.display().to_string();
    project.root_path = source_str.clone();
    project.source_path = source_str;
    Ok(())
}

/// Disk projects: record-only at attach time; the content copy into
/// `<workspace>/config/non-local-package/<package name>/` happens on the
/// explicit record action. The package name doubles as the later folder
/// name, so it must be unique across all disk projects of every queue.
fn prepare_disk_project(
    app: &tauri::AppHandle,
    project: &mut ConfigProject,
) -> Result<(), String> {
    let package_name = project
        .package_name
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .ok_or_else(|| "请输入项目包名".to_string())?
        .to_string();
    validate_folder_segment(&package_name)?;
    let taken = load_queues(app)?.iter().any(|queue| {
        queue.projects.iter().any(|p| {
            p.uuid != project.uuid
                && p.source == "disk"
                && p.package_name.as_deref() == Some(package_name.as_str())
        })
    });
    if taken {
        return Err(format!("包名「{package_name}」已存在，请重新输入"));
    }
    let source = PathBuf::from(project.root_path.trim());
    if !source.is_dir() {
        return Err("所选目录不存在，请重新选择".to_string());
    }
    project.source_path = source.display().to_string();
    project.package_name = Some(package_name);
    Ok(())
}

/// Rejects characters that are invalid inside a Windows folder name.
fn validate_folder_segment(segment: &str) -> Result<(), String> {
    if segment.contains(['\\', '/', ':', '*', '?', '"', '<', '>', '|']) {
        return Err("包名不能包含 \\ / : * ? \" < > | 等特殊字符".to_string());
    }
    Ok(())
}

/// Attaches a sub project to the queue identified by `queue_uuid`. Only
/// the card info is recorded here; the content copy into the config area
/// happens later through the explicit record actions (记录项目 /
/// 记录全部项目).
#[tauri::command]
pub async fn add_config_project(
    app: tauri::AppHandle,
    queue_uuid: String,
    project: ConfigProject,
) -> Result<ConfigQueue, String> {
    tauri::async_runtime::spawn_blocking(move || run_add_project(&app, &queue_uuid, project))
        .await
        .map_err(|e| e.to_string())?
}

fn run_add_project(
    app: &tauri::AppHandle,
    queue_uuid: &str,
    mut project: ConfigProject,
) -> Result<ConfigQueue, String> {
    let queue_uuid = queue_uuid.trim().to_string();
    if project.name.trim().is_empty() {
        return Err("项目名称不能为空".to_string());
    }
    if project.root_path.trim().is_empty() {
        return Err("项目路径不能为空".to_string());
    }
    let mut list = load_queues(&app)?;
    {
        let queue = list
            .iter_mut()
            .find(|q| q.uuid == queue_uuid)
            .ok_or_else(|| "未找到要添加项目的配置队列".to_string())?;
        if is_duplicate(queue, &project) {
            return Err("该项目已在队列中，无需重复添加".to_string());
        }
    }
    match project.source.as_str() {
        "imported" => prepare_imported_project(&app, &mut project)?,
        "disk" => prepare_disk_project(&app, &mut project)?,
        _ => {}
    }
    let queue = list
        .iter_mut()
        .find(|q| q.uuid == queue_uuid)
        .ok_or_else(|| "未找到要添加项目的配置队列".to_string())?;
    queue.projects.push(project);
    let updated = queue.clone();
    save_queues(&app, &list)?;
    Ok(updated)
}

/// Copies one project's contents into the config area and marks it as
/// recorded: imported projects copy from the import area's package folder
/// into `config/package/<package name>/`, disk projects copy from the
/// picked directory into `config/non-local-package/<package name>/`.
fn record_project(app: &tauri::AppHandle, project: &mut ConfigProject) -> Result<(), String> {
    let package_name = project
        .package_name
        .clone()
        .filter(|s| !s.is_empty())
        .ok_or_else(|| format!("项目「{}」缺少包名信息，无法记录", project.name))?;
    let (source, target) = match project.source.as_str() {
        "imported" => {
            let fallback = workspace_dir(app)?
                .join("import")
                .join("package")
                .join(&package_name);
            let source = if project.source_path.is_empty() {
                fallback
            } else {
                PathBuf::from(&project.source_path)
            };
            (source, config_dir(app)?.join("package").join(&package_name))
        }
        _ => {
            let source = if project.source_path.is_empty() {
                PathBuf::from(&project.root_path)
            } else {
                PathBuf::from(&project.source_path)
            };
            (
                source,
                config_dir(app)?.join("non-local-package").join(&package_name),
            )
        }
    };
    if !source.is_dir() {
        return Err(format!("项目「{}」的源目录不存在，无法记录", project.name));
    }
    if target.is_dir() {
        fs::remove_dir_all(&target).map_err(|e| format!("清空配置目录失败：{e}"))?;
    }
    copy_dir_all(&source, &target)
        .map_err(|e| format!("记录项目「{}」的内容失败：{e}", project.name))?;
    project.recorded = true;
    project.root_path = target.display().to_string();
    Ok(())
}

/// Records one sub project of the queue. Runs on the async thread pool so
/// the UI stays responsive for large projects.
#[tauri::command]
pub async fn record_config_project(
    app: tauri::AppHandle,
    queue_uuid: String,
    project_uuid: String,
) -> Result<ConfigQueue, String> {
    tauri::async_runtime::spawn_blocking(move || {
        run_record_project(&app, &queue_uuid, &project_uuid)
    })
    .await
    .map_err(|e| e.to_string())?
}

fn run_record_project(
    app: &tauri::AppHandle,
    queue_uuid: &str,
    project_uuid: &str,
) -> Result<ConfigQueue, String> {
    let mut list = load_queues(app)?;
    {
        let project = find_project_mut(&mut list, queue_uuid, project_uuid)?;
        record_project(app, project)?;
    }
    let updated = list
        .iter()
        .find(|q| q.uuid == queue_uuid)
        .cloned()
        .ok_or_else(|| "未找到配置队列".to_string())?;
    save_queues(app, &list)?;
    Ok(updated)
}

/// Records every project of the queue (imported projects from the import
/// area, disk projects from their disk directories). Already-recorded
/// projects are refreshed. Runs on the async thread pool.
#[tauri::command]
pub async fn record_all_config_projects(
    app: tauri::AppHandle,
    queue_uuid: String,
) -> Result<ConfigQueue, String> {
    tauri::async_runtime::spawn_blocking(move || run_record_all_projects(&app, &queue_uuid))
        .await
        .map_err(|e| e.to_string())?
}

fn run_record_all_projects(
    app: &tauri::AppHandle,
    queue_uuid: &str,
) -> Result<ConfigQueue, String> {
    let mut list = load_queues(app)?;
    let first_error = {
        let queue = list
            .iter_mut()
            .find(|q| q.uuid == queue_uuid)
            .ok_or_else(|| "未找到配置队列".to_string())?;
        let mut error = None;
        for project in queue.projects.iter_mut() {
            if let Err(e) = record_project(app, project) {
                if error.is_none() {
                    error = Some(e);
                }
            }
        }
        error
    };
    let updated = list
        .iter()
        .find(|q| q.uuid == queue_uuid)
        .cloned()
        .ok_or_else(|| "未找到配置队列".to_string())?;
    // Persist whatever was recorded successfully, then report the failure.
    save_queues(app, &list)?;
    if let Some(e) = first_error {
        return Err(e);
    }
    Ok(updated)
}

/// Removes a sub project from its queue by project uuid; the underlying
/// files are never touched.
#[tauri::command]
pub fn remove_config_project(
    app: tauri::AppHandle,
    queue_uuid: String,
    project_uuid: String,
) -> Result<ConfigQueue, String> {
    let queue_uuid = queue_uuid.trim().to_string();
    let project_uuid = project_uuid.trim().to_string();
    let mut list = load_queues(&app)?;
    let queue = list
        .iter_mut()
        .find(|q| q.uuid == queue_uuid)
        .ok_or_else(|| "未找到配置队列".to_string())?;
    let before = queue.projects.len();
    queue.projects.retain(|p| p.uuid != project_uuid);
    if queue.projects.len() == before {
        return Err("未找到要删除的项目".to_string());
    }
    let updated = queue.clone();
    save_queues(&app, &list)?;
    Ok(updated)
}

fn find_project_mut<'a>(
    list: &'a mut [ConfigQueue],
    queue_uuid: &str,
    project_uuid: &str,
) -> Result<&'a mut ConfigProject, String> {
    let queue = list
        .iter_mut()
        .find(|q| q.uuid == queue_uuid)
        .ok_or_else(|| "未找到配置队列".to_string())?;
    queue
        .projects
        .iter_mut()
        .find(|p| p.uuid == project_uuid)
        .ok_or_else(|| "未找到项目".to_string())
}

/// Saves the selected template name and the modify-config time for one
/// sub project without starting the configuration.
#[tauri::command]
pub fn save_config_template(
    app: tauri::AppHandle,
    queue_uuid: String,
    project_uuid: String,
    template_name: String,
    config_time: String,
) -> Result<ConfigQueue, String> {
    let queue_uuid = queue_uuid.trim().to_string();
    let project_uuid = project_uuid.trim().to_string();
    let template_name = template_name.trim().to_string();
    if template_name.is_empty() {
        return Err("请选择配置模板".to_string());
    }
    let mut list = load_queues(&app)?;
    {
        let project = find_project_mut(&mut list, &queue_uuid, &project_uuid)?;
        project.template_name = Some(template_name);
        project.config_time = Some(config_time);
    }
    let updated = list
        .iter()
        .find(|q| q.uuid == queue_uuid)
        .cloned()
        .ok_or_else(|| "未找到配置队列".to_string())?;
    save_queues(&app, &list)?;
    Ok(updated)
}

/// Marks a sub project as configured (已配置) and records the start
/// time. Starting requires a previously saved template.
#[tauri::command]
pub fn start_config_project(
    app: tauri::AppHandle,
    queue_uuid: String,
    project_uuid: String,
    started_at: String,
) -> Result<ConfigQueue, String> {
    let queue_uuid = queue_uuid.trim().to_string();
    let project_uuid = project_uuid.trim().to_string();
    let mut list = load_queues(&app)?;
    {
        let project = find_project_mut(&mut list, &queue_uuid, &project_uuid)?;
        if project.template_name.is_none() {
            return Err("该项目未选择配置模板，无法开始配置".to_string());
        }
        project.started = true;
        project.started_at = Some(started_at);
    }
    let updated = list
        .iter()
        .find(|q| q.uuid == queue_uuid)
        .cloned()
        .ok_or_else(|| "未找到配置队列".to_string())?;
    save_queues(&app, &list)?;
    Ok(updated)
}

/// Deletes queues by uuid (single and batch deletion share this command).
/// The embedded project records are removed with their queue; the copied
/// folders on disk are kept.
#[tauri::command]
pub fn delete_config_queues(app: tauri::AppHandle, uuids: Vec<String>) -> Result<(), String> {
    let targets: HashSet<String> = uuids.iter().map(|u| u.trim().to_string()).collect();
    if targets.is_empty() {
        return Ok(());
    }
    let mut list = load_queues(&app)?;
    if !list.iter().any(|q| targets.contains(&q.uuid)) {
        return Err("未找到要删除的队列".to_string());
    }
    list.retain(|q| !targets.contains(&q.uuid));
    save_queues(&app, &list)
}

/// Updates a disk (non-imported) project's name and package name; the
/// copied folder under `non-local-package/` is renamed to match the new
/// package name. Imported projects are read-only here.
#[tauri::command]
pub fn update_config_project(
    app: tauri::AppHandle,
    queue_uuid: String,
    project_uuid: String,
    new_name: String,
    new_package_name: String,
) -> Result<ConfigQueue, String> {
    let queue_uuid = queue_uuid.trim().to_string();
    let project_uuid = project_uuid.trim().to_string();
    let new_name = new_name.trim().to_string();
    let new_package_name = new_package_name.trim().to_string();
    if new_name.is_empty() {
        return Err("项目名称不能为空".to_string());
    }
    if new_package_name.is_empty() {
        return Err("项目包名不能为空".to_string());
    }
    validate_folder_segment(&new_package_name)?;

    let mut list = load_queues(&app)?;
    // The package name doubles as a folder name, so it must stay unique
    // among the other disk projects.
    let taken = list.iter().flat_map(|q| q.projects.iter()).any(|p| {
        p.uuid != project_uuid
            && p.source == "disk"
            && p.package_name.as_deref() == Some(new_package_name.as_str())
    });
    if taken {
        return Err(format!(
            "包名「{new_package_name}」已被其他项目使用，请重新输入"
        ));
    }

    let project = find_project_mut(&mut list, &queue_uuid, &project_uuid)?;
    if project.source != "disk" {
        return Err("导入项目的信息不支持修改".to_string());
    }
    let old_package = project.package_name.clone().unwrap_or_default();
    if old_package != new_package_name {
        let base = config_dir(&app)?.join("non-local-package");
        let from = base.join(&old_package);
        let to = base.join(&new_package_name);
        if to.exists() {
            return Err(format!(
                "「{new_package_name}」对应的文件夹已存在，请重新输入包名"
            ));
        }
        if from.is_dir() {
            fs::rename(&from, &to)
                .map_err(|e| format!("重命名项目文件夹失败：{e}"))?;
        }
        project.root_path = to.display().to_string();
    }
    project.name = new_name;
    project.package_name = Some(new_package_name);
    let updated = list
        .iter()
        .find(|q| q.uuid == queue_uuid)
        .cloned()
        .ok_or_else(|| "未找到配置队列".to_string())?;
    save_queues(&app, &list)?;
    Ok(updated)
}

/// Imported projects: clears the copied `<workspace>/config/package/<package
/// name>/` folder and copies the import area's contents in again. Runs on
/// the async thread pool so the UI stays responsive for large projects.
#[tauri::command]
pub async fn reload_config_project(
    app: tauri::AppHandle,
    queue_uuid: String,
    project_uuid: String,
) -> Result<ConfigQueue, String> {
    tauri::async_runtime::spawn_blocking(move || {
        run_reload_project(&app, &queue_uuid, &project_uuid)
    })
    .await
    .map_err(|e| e.to_string())?
}

fn run_reload_project(
    app: &tauri::AppHandle,
    queue_uuid: &str,
    project_uuid: &str,
) -> Result<ConfigQueue, String> {
    let mut list = load_queues(app)?;
    let package_name = {
        let project = find_project_mut(&mut list, queue_uuid, project_uuid)?;
        if project.source != "imported" {
            return Err("仅导入项目支持重新在导入区加载".to_string());
        }
        project
            .package_name
            .clone()
            .filter(|s| !s.is_empty())
            .ok_or_else(|| "导入项目缺少包名信息".to_string())?
    };
    let source = workspace_dir(app)?
        .join("import")
        .join("package")
        .join(&package_name);
    if !source.is_dir() {
        return Err(format!(
            "导入区未找到包名「{package_name}」的内容，请先在导入区完成导入"
        ));
    }
    let target = config_dir(app)?.join("package").join(&package_name);
    if target.is_dir() {
        fs::remove_dir_all(&target).map_err(|e| format!("清空配置目录失败：{e}"))?;
    }
    copy_dir_all(&source, &target)
        .map_err(|e| format!("重新加载包名「{package_name}」的内容失败：{e}"))?;
    list.iter()
        .find(|q| q.uuid == queue_uuid)
        .cloned()
        .ok_or_else(|| "未找到配置队列".to_string())
}
/// Deletes sub projects by uuid across every queue (single and batch
/// deletion share this command) and removes each project's copied folder
/// under the config area. Folders still referenced by a remaining project
/// are kept. The folder removal runs on the async thread pool so the UI
/// stays responsive for large projects.
#[tauri::command]
pub async fn delete_config_projects(
    app: tauri::AppHandle,
    project_uuids: Vec<String>,
) -> Result<(), String> {
    tauri::async_runtime::spawn_blocking(move || run_delete_projects(&app, project_uuids))
        .await
        .map_err(|e| e.to_string())?
}

fn run_delete_projects(
    app: &tauri::AppHandle,
    project_uuids: Vec<String>,
) -> Result<(), String> {
    let targets: HashSet<String> = project_uuids
        .iter()
        .map(|u| u.trim().to_string())
        .collect();
    if targets.is_empty() {
        return Ok(());
    }
    let mut list = load_queues(&app)?;

    // Collect the copied folders of the removed projects.
    let mut removed_paths: Vec<PathBuf> = Vec::new();
    for queue in list.iter_mut() {
        for project in queue.projects.iter().filter(|p| targets.contains(&p.uuid)) {
            removed_paths.push(PathBuf::from(project.root_path.clone()));
        }
        queue.projects.retain(|p| !targets.contains(&p.uuid));
    }
    if removed_paths.is_empty() {
        return Err("未找到要删除的项目".to_string());
    }

    // Never remove folders that a remaining project still points at.
    let kept: HashSet<PathBuf> = list
        .iter()
        .flat_map(|q| q.projects.iter().map(|p| PathBuf::from(p.root_path.clone())))
        .collect();
    let config = config_dir(&app)?;
    for path in removed_paths {
        if kept.contains(&path) || !path.starts_with(&config) {
            continue;
        }
        if path.is_dir() {
            fs::remove_dir_all(&path)
                .map_err(|e| format!("无法删除配置目录 {}：{e}", path.display()))?;
        }
    }

    save_queues(&app, &list)
}
