use std::collections::HashSet;
use std::fs;
use std::path::PathBuf;
use serde::{Deserialize, Serialize};

use crate::android_projects::{load_projects, save_projects};
use crate::core::settings::read_settings;

/// One import queue entry. All queues persist as a JSON list in
/// `<workspace>/import/queues.json` (the import page's workspace folder).
#[derive(Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ImportQueue {
    pub name: String,
    pub uuid: String,
    pub queue_type: String,
    pub created_at: String,
    /// Package names of the Android projects attached to this queue
    /// (their full records live in `android.json`).
    #[serde(default)]
    pub packages: Vec<String>,
}

fn workspace_dir(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    let settings = read_settings(app);
    let trimmed = settings.workspace_path.trim().to_string();
    if trimmed.is_empty() {
        return Err("请先在「设置 → 存储」中选择工作空间路径".to_string());
    }
    let dir = PathBuf::from(trimmed);
    if !dir.is_dir() {
        return Err("工作空间路径不存在，请重新选择".to_string());
    }
    Ok(dir)
}

fn import_dir(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    Ok(workspace_dir(app)?.join("import"))
}

fn queues_path(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    Ok(import_dir(app)?.join("queues.json"))
}

pub fn load_queues(app: &tauri::AppHandle) -> Result<Vec<ImportQueue>, String> {
    let path = queues_path(app)?;
    match fs::read_to_string(&path) {
        Ok(content) => Ok(serde_json::from_str(&content).unwrap_or_default()),
        Err(_) => Ok(Vec::new()),
    }
}

pub fn save_queues(app: &tauri::AppHandle, list: &[ImportQueue]) -> Result<(), String> {
    let dir = import_dir(app)?;
    fs::create_dir_all(&dir).map_err(|e| format!("无法创建导入区目录：{e}"))?;
    let content = serde_json::to_string_pretty(list).map_err(|e| e.to_string())?;
    fs::write(queues_path(app)?, content).map_err(|e| e.to_string())
}

#[tauri::command]
pub fn list_import_queues(app: tauri::AppHandle) -> Result<Vec<ImportQueue>, String> {
    load_queues(&app)
}

/// Creates a new import queue. The uuid is generated by the frontend and
/// must be unique across all queues; the timestamp comes from the frontend
/// in local time (`YYYY-MM-DD HH:mm:ss`) and is stored as-is.
#[tauri::command]
pub fn create_import_queue(
    app: tauri::AppHandle,
    name: String,
    uuid: String,
    queue_type: String,
    created_at: String,
) -> Result<ImportQueue, String> {
    let name = name.trim().to_string();
    if name.is_empty() {
        return Err("队列名称不能为空".to_string());
    }
    let uuid = uuid.trim().to_string();
    if uuid.is_empty() {
        return Err("队列编号不能为空".to_string());
    }
    let mut list = load_queues(&app)?;
    if list.iter().any(|q| q.uuid == uuid) {
        return Err("队列编号已存在，请重新生成".to_string());
    }

    let queue = ImportQueue {
        name,
        uuid,
        queue_type: queue_type.trim().to_string(),
        created_at,
        packages: Vec::new(),
    };
    list.push(queue.clone());
    save_queues(&app, &list)?;
    Ok(queue)
}

/// Deletes one or more queues by uuid (single and batch deletion share this
/// command). Attached Android projects are not deleted: their records stay
/// in `android.json` with the queue reference cleared, so they remain
/// visible in the import directory.
#[tauri::command]
pub fn delete_queues(app: tauri::AppHandle, uuids: Vec<String>) -> Result<(), String> {
    let targets: HashSet<String> = uuids.iter().map(|u| u.trim().to_string()).collect();
    if targets.is_empty() {
        return Ok(());
    }
    let mut list = load_queues(&app)?;
    let removed: Vec<String> = list
        .iter()
        .filter(|q| targets.contains(&q.uuid))
        .map(|q| q.uuid.clone())
        .collect();
    if removed.is_empty() {
        return Err("未找到要删除的队列".to_string());
    }
    list.retain(|q| !targets.contains(&q.uuid));
    save_queues(&app, &list)?;

    // Detach the attached projects instead of deleting them.
    let removed_set: HashSet<&String> = removed.iter().collect();
    let mut projects = load_projects(&app)?;
    let mut changed = false;
    for project in projects.iter_mut() {
        if removed_set.contains(&project.queue_uuid) {
            project.queue_uuid.clear();
            changed = true;
        }
    }
    if changed {
        save_projects(&app, &projects)?;
    }
    Ok(())
}
