use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};

use crate::common::storage::{copy_dir_complete, verify_file_copy};
use crate::core::settings::read_settings;

/// A template type entry shown on the templates page.
#[derive(Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct TemplateInfo {
    pub name: String,
    pub template_type: String,
    pub description: String,
    pub created_at: String,
    pub updated_at: String,
    /// Whether the `code` subfolder has been imported at least once.
    #[serde(default)]
    pub code_imported: bool,
    /// Whether the `parameter` subfolder has been imported at least once.
    #[serde(default)]
    pub parameter_imported: bool,
}

fn workspace_dir(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    let settings = read_settings(app);
    let trimmed = settings.workspace_path.trim().to_string();
    if trimmed.is_empty() {
        return Err("请先在「设置 → 存储」中选择工作空间路径".to_string());
    }
    let dir = PathBuf::from(trimmed);
    if !dir.is_dir() {
        return Err("工作空间路径不存在，请重新选择".to_string());
    }
    Ok(dir)
}

/// Templates persist as JSON under `<workspace>/templates/`; the directory
/// is named after the page's English name.
fn templates_dir(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    Ok(workspace_dir(app)?.join("templates"))
}

fn templates_path(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    Ok(templates_dir(app)?.join("templates.json"))
}

fn load_list(app: &tauri::AppHandle) -> Result<Vec<TemplateInfo>, String> {
    let path = templates_path(app)?;
    match fs::read_to_string(&path) {
        Ok(content) => Ok(serde_json::from_str(&content).unwrap_or_default()),
        Err(_) => Ok(Vec::new()),
    }
}

fn save_list(app: &tauri::AppHandle, list: &[TemplateInfo]) -> Result<(), String> {
    let dir = templates_dir(app)?;
    fs::create_dir_all(&dir).map_err(|e| format!("无法创建模板目录：{e}"))?;
    let content = serde_json::to_string_pretty(list).map_err(|e| e.to_string())?;
    fs::write(templates_path(app)?, content).map_err(|e| e.to_string())
}

/// Resolves the on-disk directory of an existing template:
/// `<workspace>/templates/<name>/`.
fn template_dir(app: &tauri::AppHandle, name: &str) -> Result<PathBuf, String> {
    let list = load_list(app)?;
    if !list.iter().any(|t| t.name == name) {
        return Err(format!("模板「{name}」不存在"));
    }
    Ok(templates_dir(app)?.join(name))
}

#[tauri::command]
pub fn list_templates(app: tauri::AppHandle) -> Result<Vec<TemplateInfo>, String> {
    load_list(&app)
}

/// Creates a new template entry. The timestamps are generated by the
/// frontend in local time (`YYYY-MM-DD HH:mm:ss`) and stored as-is.
/// Also creates the template folder with `code`/`parameter` subfolders.
#[tauri::command]
pub fn create_template(
    app: tauri::AppHandle,
    name: String,
    template_type: String,
    description: String,
    created_at: String,
    updated_at: String,
) -> Result<TemplateInfo, String> {
    let name = name.trim().to_string();
    if name.is_empty() {
        return Err("模板名称不能为空".to_string());
    }
    let mut list = load_list(&app)?;
    if list.iter().any(|t| t.name == name) {
        return Err(format!("模板「{name}」已存在"));
    }

    // Folder named after the template, holding code/ and parameter/.
    let dir = templates_dir(&app)?.join(&name);
    fs::create_dir_all(dir.join("code"))
        .map_err(|e| format!("无法创建模板文件夹：{e}"))?;
    fs::create_dir_all(dir.join("parameter"))
        .map_err(|e| format!("无法创建模板文件夹：{e}"))?;

    let info = TemplateInfo {
        name,
        template_type: template_type.trim().to_string(),
        description: description.trim().to_string(),
        created_at,
        updated_at,
        code_imported: false,
        parameter_imported: false,
    };
    list.push(info.clone());
    save_list(&app, &list)?;
    Ok(info)
}

/// Updates an existing template entry identified by `original_name`. The
/// creation time is preserved; the update time comes from the frontend.
#[tauri::command]
pub fn update_template(
    app: tauri::AppHandle,
    original_name: String,
    name: String,
    template_type: String,
    description: String,
    updated_at: String,
) -> Result<TemplateInfo, String> {
    let original_name = original_name.trim().to_string();
    let name = name.trim().to_string();
    if name.is_empty() {
        return Err("模板名称不能为空".to_string());
    }
    let mut list = load_list(&app)?;
    let Some(index) = list.iter().position(|t| t.name == original_name) else {
        return Err(format!("模板「{original_name}」不存在"));
    };
    if name != original_name && list.iter().any(|t| t.name == name) {
        return Err(format!("模板「{name}」已存在"));
    }

    // Keep the on-disk folder in sync with a renamed template.
    if name != original_name {
        let base = templates_dir(&app)?;
        let old_dir = base.join(&original_name);
        if old_dir.is_dir() {
            fs::rename(&old_dir, base.join(&name))
                .map_err(|e| format!("无法重命名模板文件夹：{e}"))?;
        }
        // Config projects referencing the old name follow the rename.
        crate::configs::rename_template_refs(&app, &original_name, &name);
    }

    let info = TemplateInfo {
        name,
        template_type: template_type.trim().to_string(),
        description: description.trim().to_string(),
        created_at: list[index].created_at.clone(),
        updated_at,
        code_imported: list[index].code_imported,
        parameter_imported: list[index].parameter_imported,
    };
    list[index] = info.clone();
    save_list(&app, &list)?;
    Ok(info)
}

/// Deletes one or more templates by name. Used for both the single
/// delete action and the batch delete in selection mode.
#[tauri::command]
pub fn delete_templates(app: tauri::AppHandle, names: Vec<String>) -> Result<(), String> {
    let targets: HashSet<String> = names.iter().map(|n| n.trim().to_string()).collect();
    if targets.is_empty() {
        return Ok(());
    }
    let mut list = load_list(&app)?;
    let removed: Vec<String> = list
        .iter()
        .filter(|t| targets.contains(&t.name))
        .map(|t| t.name.clone())
        .collect();
    if removed.is_empty() {
        return Err("未找到要删除的模板".to_string());
    }
    list.retain(|t| !targets.contains(&t.name));
    save_list(&app, &list)?;
    // Config projects referencing the deleted templates fall back to
    // 未选择模板 instead of failing on a dangling name later.
    crate::configs::clear_template_refs(&app, &removed);

    // Cleanup of the on-disk template folders (retry once in case a
    // process such as Explorer briefly holds the directory).
    let base = templates_dir(&app)?;
    let mut failed: Vec<String> = Vec::new();
    for name in &removed {
        let dir = base.join(name);
        if !dir.is_dir() {
            continue;
        }
        if fs::remove_dir_all(&dir).is_err() {
            std::thread::sleep(std::time::Duration::from_millis(300));
            if fs::remove_dir_all(&dir).is_err() {
                failed.push(dir.display().to_string());
            }
        }
    }
    if !failed.is_empty() {
        return Err(format!(
            "模板记录已删除，但文件夹删除失败（可能被占用）：{}",
            failed.join("、")
        ));
    }
    Ok(())
}

/// Returns the on-disk directory of a template (for opening in Explorer).
#[tauri::command]
pub fn get_template_dir(app: tauri::AppHandle, name: String) -> Result<String, String> {
    template_dir(&app, name.trim()).map(|p| p.display().to_string())
}

fn parameter_json_path(app: &tauri::AppHandle, name: &str) -> Result<PathBuf, String> {
    Ok(template_dir(app, name)?.join("parameter").join(format!("{name}.json")))
}

/// Reads the template's parameter JSON file for in-app editing.
#[tauri::command]
pub fn read_parameter_json(app: tauri::AppHandle, name: String) -> Result<String, String> {
    let name = name.trim().to_string();
    let file = parameter_json_path(&app, &name)?;
    if !file.is_file() {
        return Err("尚未导入参数模板，请先导入".to_string());
    }
    fs::read_to_string(&file).map_err(|e| format!("读取参数模板失败：{e}"))
}

/// Saves edited parameter JSON content. The content is validated as JSON
/// before being written back to `<name>.json` verbatim.
#[tauri::command]
pub fn write_parameter_json(
    app: tauri::AppHandle,
    name: String,
    content: String,
) -> Result<(), String> {
    let name = name.trim().to_string();
    // Validate without reformatting the user's content.
    serde_json::from_str::<serde_json::Value>(&content)
        .map_err(|e| format!("JSON 格式错误：{e}"))?;
    let file = parameter_json_path(&app, &name)?;
    if let Some(parent) = file.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("无法创建文件夹：{e}"))?;
    }
    fs::write(&file, content).map_err(|e| format!("保存参数模板失败：{e}"))
}

/// Opens a path in the platform file manager. Spawns the OS file manager
/// directly because the opener plugin's path scope cannot cover a
/// user-chosen workspace directory.
#[tauri::command]
pub fn open_in_explorer(path: String) -> Result<(), String> {
    let target = PathBuf::from(path.trim());
    if !target.exists() {
        return Err("路径不存在".to_string());
    }
    #[cfg(windows)]
    {
        std::process::Command::new("explorer")
            .arg(&target)
            .spawn()
            .map_err(|e| format!("无法打开资源管理器：{e}"))?;
        return Ok(());
    }
    #[cfg(target_os = "macos")]
    {
        std::process::Command::new("open")
            .arg(&target)
            .spawn()
            .map_err(|e| format!("无法打开访达：{e}"))?;
        return Ok(());
    }
    #[cfg(all(unix, not(target_os = "macos")))]
    {
        std::process::Command::new("xdg-open")
            .arg(&target)
            .spawn()
            .map_err(|e| format!("无法打开文件管理器：{e}"))?;
        Ok(())
    }
}

/// Copies everything inside `source_dir` into the template's `code/`
/// subfolder, clearing the previous contents first (re-import).
#[tauri::command]
pub fn import_code_template(
    app: tauri::AppHandle,
    name: String,
    source_dir: String,
) -> Result<(), String> {
    let name = name.trim().to_string();
    let source = PathBuf::from(source_dir.trim());
    if !source.is_dir() {
        return Err("所选文件夹不存在".to_string());
    }
    let target = template_dir(&app, &name)?.join("code");
    clear_dir(&target).map_err(|e| format!("无法清空原有内容：{e}"))?;
    if let Err(e) = copy_dir_complete(&source, &target) {
        // Never leave a half-copied template folder behind.
        let _ = clear_dir(&target);
        return Err(format!("复制文件失败：{e}"));
    }
    set_import_flag(&app, &name, Some(true), None)
}

/// Copies a single JSON file into the template's `parameter/` subfolder,
/// renamed to `<template name>.json`, clearing previous contents first.
#[tauri::command]
pub fn import_parameter_template(
    app: tauri::AppHandle,
    name: String,
    source_file: String,
) -> Result<(), String> {
    let name = name.trim().to_string();
    let source = PathBuf::from(source_file.trim());
    if !source.is_file() {
        return Err("所选文件不存在".to_string());
    }
    let is_json = source
        .extension()
        .map(|ext| ext.eq_ignore_ascii_case("json"))
        .unwrap_or(false);
    if !is_json {
        return Err("只能导入 JSON 文件".to_string());
    }
    let target = template_dir(&app, &name)?.join("parameter");
    clear_dir(&target).map_err(|e| format!("无法清空原有内容：{e}"))?;
    fs::create_dir_all(&target).map_err(|e| format!("无法创建文件夹：{e}"))?;
    let dest = target.join(format!("{name}.json"));
    fs::copy(&source, &dest).map_err(|e| format!("复制文件失败：{e}"))?;
    verify_file_copy(&source, &dest)?;
    set_import_flag(&app, &name, None, Some(true))
}

fn set_import_flag(
    app: &tauri::AppHandle,
    name: &str,
    code: Option<bool>,
    parameter: Option<bool>,
) -> Result<(), String> {
    let mut list = load_list(app)?;
    let Some(item) = list.iter_mut().find(|t| t.name == name) else {
        return Err(format!("模板「{name}」不存在"));
    };
    if let Some(flag) = code {
        item.code_imported = flag;
    }
    if let Some(flag) = parameter {
        item.parameter_imported = flag;
    }
    save_list(app, &list)
}

/// Removes every entry inside `dir` without deleting `dir` itself.
fn clear_dir(dir: &Path) -> std::io::Result<()> {
    if !dir.is_dir() {
        return Ok(());
    }
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if entry.file_type()?.is_dir() {
            fs::remove_dir_all(&path)?;
        } else {
            fs::remove_file(&path)?;
        }
    }
    Ok(())
}
